# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class PersonalAccessTokensController < ApplicationController
  self.main_menu = false

  before_action :require_login
  before_action :find_token, :only => :destroy
  require_sudo_mode :create, :destroy

  def index
    @tokens = User.current.personal_access_tokens.order(:id).to_a
    # One-time display of a value generated by the create action. Deleted
    # from the flash so that render_flash_messages does not repeat it.
    @new_token_value = flash[:personal_access_token_value]
    flash.delete(:personal_access_token_value)
  end

  helper_method :default_expiration_days

  def new
    @token = PersonalAccessToken.new(:expires_on => default_expiration_days.days.from_now.to_date)
  end

  def create
    @token = PersonalAccessToken.new(:user => User.current)
    @token.safe_attributes = params[:personal_access_token]
    if @token.save
      flash[:personal_access_token_value] = @token.plaintext_value
      flash[:notice] = l(:notice_personal_access_token_created, :name => @token.name)
      redirect_to my_personal_access_tokens_path
    else
      render :action => 'new'
    end
  end

  def destroy
    @token.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to my_personal_access_tokens_path
  end

  private

  # Default expiration offered by the form, clamped to the admin
  # max-lifetime policy so the prefilled date is always valid
  def default_expiration_days
    max = Setting.personal_access_token_max_lifetime.to_i
    max > 0 ? [30, max].min : 30
  end

  def find_token
    @token = User.current.personal_access_tokens.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end
